services:
  picare-hub-server:
    image: ghcr.io/tritruong666/picare-hub-server:latest
    container_name: picare-hub-server
    restart: always
    env_file:
      - .env
    environment:
      - MAX_FILE_UPLOAD_MB=${MAX_FILE_UPLOAD_MB:-2048}
    volumes:
      - ./src/seeds/local_data:/app/src/seeds/local_data
    networks:
      - picare-network
      - web_network

networks:
  picare-network:
    external: true
  web_network:
    external: true    
