/**
 * Centralized error codes for the application.
 */
const ErrorCodes = {
  INTERNAL_SERVER_ERROR: {
    code: "ERR_INTERNAL_001",
    message: "Da co loi xay ra phia may chu",
    statusCode: 500,
  },
  BAD_REQUEST: {
    code: "ERR_BAD_REQUEST_001",
    message: "Du lieu yeu cau khong hop le",
    statusCode: 400,
  },
  UNAUTHORIZED: {
    code: "ERR_UNAUTHORIZED_001",
    message: "Phien dang nhap da het han hoac khong hop le",
    statusCode: 401,
  },
  FORBIDDEN: {
    code: "ERR_FORBIDDEN_001",
    message: "Ban khong co quyen thuc hien hanh dong nay",
    statusCode: 403,
  },
  NOT_FOUND: {
    code: "ERR_NOT_FOUND_001",
    message: "Khong tim thay tai nguyen yeu cau",
    statusCode: 404,
  },

  DATABASE_ERROR: {
    code: "ERR_DB_001",
    message: "Loi ket noi co so du lieu",
    statusCode: 500,
  },
  DUPLICATE_ENTRY: {
    code: "ERR_DB_002",
    message: "Du lieu da ton tai trong he thong",
    statusCode: 409,
  },

  AUTH_INVALID_CREDENTIALS: {
    code: "ERR_AUTH_001",
    message: "Email hoac mat khau khong chinh xac",
    statusCode: 401,
  },
  AUTH_EMAIL_TAKEN: {
    code: "ERR_AUTH_002",
    message: "Email da duoc su dung",
    statusCode: 400,
  },
  AUTH_ROLE_NOT_ALLOWED: {
    code: "ERR_AUTH_003",
    message: "Tai khoan cua ban khong co quyen truy cap vao he thong nay",
    statusCode: 403,
  },
  AUTH_OLD_PASSWORD_INCORRECT: {
    code: "ERR_AUTH_004",
    message: "Mat khau cu khong chinh xac",
    statusCode: 400,
  },
  AUTH_NEW_PASSWORD_MUST_DIFFERENT: {
    code: "ERR_AUTH_005",
    message: "Mat khau moi phai khac mat khau cu",
    statusCode: 400,
  },
  CLIENT_NOT_FOUND: {
    code: "ERR_CLIENT_001",
    message: "Khong tim thay client he thong",
    statusCode: 404,
  },

  USER_NOT_FOUND: {
    code: "ERR_USER_001",
    message: "Khong tim thay nguoi dung",
    statusCode: 400,
  },
  USER_ROLE_REQUIRED: { code: "ERR_USER_002", message: "Role khong duoc de trong", statusCode: 400 },
  COMPANY_NOT_FOUND: {
    code: "ERR_COMPANY_001",
    message: "Khong tim thay cong ty",
    statusCode: 404,
  },
  SHOP_NOT_FOUND: {
    code: "ERR_SHOP_001",
    message: "Khong tim thay shop",
    statusCode: 404,
  },
  ORDER_NOT_FOUND: {
    code: "ERR_ORDER_001",
    message: "Khong tim thay don hang",
    statusCode: 404,
  },

  APP_CONFIG_NOT_FOUND: { code: "ERR_CONFIG_001", message: "Khong tim thay cau hinh chinh trong co so du lieu", statusCode: 500 },
  FPT_AI_API_KEY_MISSING: { code: "ERR_FPT_AI_001", message: "Chua cau hinh FPT_AI_API_KEY", statusCode: 400 },
  FPT_AI_URL_MISSING: { code: "ERR_FPT_AI_002", message: "Chua cau hinh FPT_AI_ID_RECOGNITION_URL", statusCode: 400 },
  FPT_AI_INVALID_ID_IMAGE: { code: "ERR_FPT_AI_003", message: "File anh CMND/CCCD khong hop le", statusCode: 400 },
  FPT_AI_INVALID_RESPONSE: { code: "ERR_FPT_AI_004", message: "FPT AI tra ve response khong phai JSON", statusCode: 400 },
  FPT_AI_REQUEST_FAILED: { code: "ERR_FPT_AI_005", message: "Goi FPT AI that bai", statusCode: 400 },
  FPT_AI_RECOGNITION_FAILED: { code: "ERR_FPT_AI_006", message: "FPT AI khong nhan dien duoc anh CMND/CCCD", statusCode: 400 },

  LICENSE_NOT_FOUND: { code: "ERR_LICENSE_001", message: "Khong tim thay license", statusCode: 404 },
  LICENSE_SOFTWARE_NOT_FOUND: { code: "ERR_LICENSE_002", message: "Khong tim thay phan mem trong license", statusCode: 404 },
  LICENSE_TICKET_NOT_FOUND: { code: "ERR_LICENSE_003", message: "Khong tim thay ticket trong license", statusCode: 404 },
  LICENSE_CREDENTIALS_INVALID: { code: "ERR_LICENSE_004", message: "License key hoac software ID khong hop le", statusCode: 404 },
  LICENSE_SOFTWARE_INACTIVE: { code: "ERR_LICENSE_005", message: "Phan mem da bi khoa hoac dang co loi ban quyen", statusCode: 403 },
  LICENSE_SOFTWARE_NOT_SERVER: { code: "ERR_LICENSE_006", message: "Software khong phai loai server", statusCode: 400 },
  LICENSE_SERVER_INACTIVE: { code: "ERR_LICENSE_007", message: "Server da bi khoa hoac dang co loi ban quyen", statusCode: 403 },

  QR_PRODUCT_NOT_FOUND: { code: "ERR_QR_001", message: "Khong tim thay QR san pham", statusCode: 404 },
  S3_MAIN_VIDEO_NOT_FOUND: (key) => ({ code: "ERR_S3_001", message: `Video chinh khong ton tai: ${key}`, statusCode: 400 }),
  S3_SECOND_VIDEO_NOT_FOUND: (key) => ({ code: "ERR_S3_002", message: `Video phu khong ton tai: ${key}`, statusCode: 400 }),
  S3_FOLDER_DUPLICATE: (name) => ({ code: "ERR_S3_FOLDER_001", message: `Thu muc voi ten \"${name}\" da ton tai`, statusCode: 400 }),
  S3_FOLDER_NOT_FOUND: { code: "ERR_S3_FOLDER_002", message: "Khong tim thay thu muc", statusCode: 404 },
  S3_FOLDER_NAME_DUPLICATE: (name) => ({ code: "ERR_S3_FOLDER_003", message: `Ten thu muc \"${name}\" da bi trung`, statusCode: 400 }),

  HUB_CLIENT_EXTERNAL_URL_INVALID: { code: "ERR_HUB_CLIENT_002", message: "External URL khong hop le", statusCode: 400 },
  HUB_CLIENT_PERMISSION_INPUT_MISSING: { code: "ERR_HUB_CLIENT_003", message: "Thieu clientId hoac externalUrl de kiem tra quyen", statusCode: 400 },
  HUB_CLIENT_NOT_FOUND: { code: "ERR_HUB_CLIENT_004", message: "Khong tim thay Hub Client", statusCode: 404 },
  HUB_CLIENT_NAME_TAKEN: { code: "ERR_HUB_CLIENT_005", message: "Ten Hub Client da ton tai", statusCode: 400 },

  CHAT_MEMBER_REQUIRED: { code: "ERR_CHAT_001", message: "Phai co it nhat 1 thanh vien khac", statusCode: 400 },
  CHAT_PRIVATE_MEMBER_COUNT_INVALID: { code: "ERR_CHAT_002", message: "Chat rieng chi duoc co dung 2 thanh vien", statusCode: 400 },
  CHAT_GROUP_NAME_REQUIRED: { code: "ERR_CHAT_003", message: "Nhom chat phai co ten", statusCode: 400 },
  CHAT_NOT_MEMBER: { code: "ERR_CHAT_004", message: "Ban khong phai thanh vien", statusCode: 403 },
  CHAT_NOT_CONVERSATION_MEMBER: { code: "ERR_CHAT_005", message: "Ban khong phai thanh vien cua cuoc hoi thoai nay", statusCode: 403 },
  CHAT_CONVERSATION_NOT_FOUND: { code: "ERR_CHAT_006", message: "Khong tim thay cuoc hoi thoai", statusCode: 404 },
  CHAT_GROUP_UPDATE_FORBIDDEN: { code: "ERR_CHAT_007", message: "Chi owner hoac admin moi co the cap nhat nhom", statusCode: 403 },
  CHAT_ONLY_GROUP_UPDATE: { code: "ERR_CHAT_008", message: "Chi co the cap nhat thong tin nhom chat", statusCode: 400 },
  CHAT_ADD_MEMBER_FORBIDDEN: { code: "ERR_CHAT_009", message: "Chi owner/admin moi duoc them thanh vien", statusCode: 403 },
  CHAT_ONLY_GROUP_ADD_MEMBER: { code: "ERR_CHAT_010", message: "Chi co the them thanh vien vao nhom chat", statusCode: 400 },
  CHAT_REMOVE_MEMBER_FORBIDDEN: { code: "ERR_CHAT_011", message: "Chi owner/admin moi co the xoa thanh vien", statusCode: 403 },
  CHAT_MESSAGE_EMPTY: { code: "ERR_CHAT_012", message: "Noi dung tin nhan khong duoc de trong", statusCode: 400 },
  CHAT_MESSAGE_NOT_FOUND: { code: "ERR_CHAT_013", message: "Khong tim thay tin nhan", statusCode: 404 },
  CHAT_EDIT_OWN_MESSAGE_ONLY: { code: "ERR_CHAT_014", message: "Ban chi co the chinh sua tin nhan cua chinh minh", statusCode: 403 },
  CHAT_TEXT_MESSAGE_EDIT_ONLY: { code: "ERR_CHAT_015", message: "Chi co the chinh sua tin nhan van ban", statusCode: 400 },
  CHAT_DELETE_OWN_MESSAGE_ONLY: { code: "ERR_CHAT_016", message: "Ban chi co the xoa tin nhan cua chinh minh", statusCode: 403 },

  MAIL_SMTP_CONFIG_MISSING: (fields) => ({ code: "ERR_MAIL_001", message: `Thieu cau hinh SMTP: ${fields.join(", ")}`, statusCode: 500 }),
  MAIL_TO_REQUIRED: { code: "ERR_MAIL_002", message: "Truong to la bat buoc", statusCode: 400 },
  MAIL_SUBJECT_REQUIRED: { code: "ERR_MAIL_003", message: "Truong subject la bat buoc", statusCode: 400 },
  MAIL_CONTENT_REQUIRED: { code: "ERR_MAIL_004", message: "Phai co it nhat text hoac html", statusCode: 400 },
  MAIL_SEND_FAILED: (message) => ({ code: "ERR_MAIL_005", message: `Gui mail that bai: ${message}`, statusCode: 500 }),

  CONTRACT_DRAFT_MUST_BE_PUBLISHED: { code: "ERR_CONTRACT_001", message: "Hop dong dang o trang thai nhap, can phat hanh ban unsigned truoc khi ky", statusCode: 400 },
  CONTRACT_SIGNING_COMPLETED: { code: "ERR_CONTRACT_002", message: "Hop dong da hoan tat ky", statusCode: 400 },
  CONTRACT_OWNER_MUST_SIGN_FIRST: { code: "ERR_CONTRACT_003", message: "Owner phai ky truoc", statusCode: 400 },
  CONTRACT_PARTNER_MUST_SIGN_AFTER_OWNER: { code: "ERR_CONTRACT_004", message: "Partner phai ky sau khi owner da ky", statusCode: 400 },
  CONTRACT_SIGNER_TYPE_REQUIRED: { code: "ERR_CONTRACT_005", message: "Doi tac phai cap nhat signerType truoc khi thuc hien flow ky", statusCode: 400 },
  CONTRACT_INDIVIDUAL_ID_REQUIRED: { code: "ERR_CONTRACT_006", message: "Doi tac ca nhan phai upload du 2 mat CMND/CCCD truoc khi ky tay", statusCode: 400 },
  CONTRACT_ORGANIZATION_LICENSE_REQUIRED: { code: "ERR_CONTRACT_007", message: "Doi tac to chuc phai upload giay phep kinh doanh truoc khi ky so", statusCode: 400 },
  CONTRACT_DRAFT_DOWNLOAD_ONLY: { code: "ERR_CONTRACT_008", message: "Chi co the tai ban hop dong nhap khi hop dong dang o trang thai draft", statusCode: 400 },
  CONTRACT_PDF_INVALID: { code: "ERR_CONTRACT_009", message: "File hop dong phai la PDF hop le", statusCode: 400 },
  CONTRACT_NUMBER_TAKEN: { code: "ERR_CONTRACT_010", message: "So hop dong da ton tai", statusCode: 400 },
  CONTRACT_DRAFT_PUBLISH_ONLY: { code: "ERR_CONTRACT_011", message: "Chi co the phat hanh hop dong dang o trang thai nhap", statusCode: 400 },
  CONTRACT_OWNER_SIGNED_PUBLISH_ONLY: { code: "ERR_CONTRACT_012", message: "Chi co the publish hop dong dang o trang thai owner_signed", statusCode: 400 },
  CONTRACT_LATEST_NOT_OWNER_SIGNED: { code: "ERR_CONTRACT_013", message: "Phien ban hop dong moi nhat khong o trang thai owner_signed", statusCode: 400 },
  CONTRACT_COMPLETED_PUBLISH_ONLY: { code: "ERR_CONTRACT_014", message: "Chi co the publish hop dong dang o trang thai completed", statusCode: 400 },
  CONTRACT_LATEST_NOT_COMPLETED: { code: "ERR_CONTRACT_015", message: "Phien ban hop dong moi nhat khong o trang thai completed", statusCode: 400 },
  CONTRACT_DRAFT_UPDATE_ONLY: { code: "ERR_CONTRACT_016", message: "Chi duoc cap nhat hop dong o trang thai draft", statusCode: 400 },
  CONTRACT_INDIVIDUAL_DIGITAL_SIGNATURE_UNAVAILABLE: { code: "ERR_CONTRACT_017", message: "Doi tac ca nhan khong co chu ky so, vui long su dung flow ky tay", statusCode: 400 },
  CONTRACT_SIGNING_SESSION_NOT_PENDING: { code: "ERR_CONTRACT_018", message: "Phien ky khong con o trang thai pending", statusCode: 400 },
  CONTRACT_SIGNER_TYPE_UPDATE_COMPLETED: { code: "ERR_CONTRACT_019", message: "Hop dong da hoan tat, khong the cap nhat signerType", statusCode: 400 },
  CONTRACT_TWO_ID_IMAGES_REQUIRED: { code: "ERR_CONTRACT_020", message: "Can upload du 2 anh CMND/CCCD mat truoc va mat sau", statusCode: 400 },
  CONTRACT_SIGNER_TYPE_REQUIRED_FOR_INDIVIDUAL: { code: "ERR_CONTRACT_021", message: "Vui long cap nhat signerType truoc khi upload ho so ca nhan", statusCode: 400 },
  CONTRACT_INDIVIDUAL_UPLOAD_ONLY: { code: "ERR_CONTRACT_022", message: "Chi signerType individual moi duoc upload CMND/CCCD", statusCode: 400 },
  CONTRACT_BUSINESS_LICENSE_REQUIRED: { code: "ERR_CONTRACT_023", message: "Giay phep kinh doanh la bat buoc", statusCode: 400 },
  CONTRACT_SIGNER_TYPE_REQUIRED_FOR_ORGANIZATION: { code: "ERR_CONTRACT_024", message: "Vui long cap nhat signerType truoc khi upload ho so to chuc", statusCode: 400 },
  CONTRACT_ORGANIZATION_UPLOAD_ONLY: { code: "ERR_CONTRACT_025", message: "Chi signerType organization moi duoc upload ho so to chuc", statusCode: 400 },
  CONTRACT_CREDENTIAL_TYPE_INVALID: { code: "ERR_CONTRACT_026", message: "credentialType chi nhan individual hoac organization", statusCode: 400 },
  CONTRACT_CREDENTIAL_DELETE_COMPLETED: { code: "ERR_CONTRACT_027", message: "Hop dong da hoan tat, khong the xoa ho so ky", statusCode: 400 },
  CONTRACT_HANDWRITTEN_SIGNER_TYPE_REQUIRED: { code: "ERR_CONTRACT_028", message: "Doi tac phai cap nhat signerType truoc khi thuc hien flow ky tay", statusCode: 400 },
  CONTRACT_SIGNER_TYPE_INVALID: { code: "ERR_CONTRACT_029", message: "signerType chi nhan individual hoac organization", statusCode: 400 },
  CONTRACT_SIGNER_TYPE_MISMATCH: { code: "ERR_CONTRACT_030", message: "signerType khong khop voi loai doi tac da cap nhat tren hop dong", statusCode: 400 },
  CONTRACT_ORGANIZATION_DIGITAL_FLOW_REQUIRED: { code: "ERR_CONTRACT_031", message: "Doi tac to chuc phai su dung flow ky so", statusCode: 400 },
  CONTRACT_PARTNER_SIGN_LINK_STATE_INVALID: { code: "ERR_CONTRACT_032", message: "Chi co the sinh link ky cho doi tac khi hop dong o trang thai doi tac ky (owner_signed)", statusCode: 400 },
  CONTRACT_UNSIGNED_PUBLISH_ONLY: { code: "ERR_CONTRACT_033", message: "Chi co the phat hanh hop dong dang o trang thai unsigned", statusCode: 400 },
  CONTRACT_PUBLISH_STATUS_INVALID: { code: "ERR_CONTRACT_034", message: "Trang thai hop dong khong hop le de publish", statusCode: 400 },
  CONTRACT_IMAGE_OR_PDF_REQUIRED: { code: "ERR_CONTRACT_035", message: "File phai la anh hoac PDF", statusCode: 400 },
  CONTRACT_IMAGE_REQUIRED: { code: "ERR_CONTRACT_036", message: "File phai la anh", statusCode: 400 },
  CONTRACT_ID_FRONT_IMAGE_INVALID: { code: "ERR_CONTRACT_037", message: "Anh mat truoc CMND/CCCD khong hop le", statusCode: 400 },
  CONTRACT_ID_BACK_IMAGE_INVALID: { code: "ERR_CONTRACT_038", message: "Anh mat sau CMND/CCCD khong hop le", statusCode: 400 },
  CONTRACT_BUSINESS_LICENSE_FILE_INVALID: { code: "ERR_CONTRACT_039", message: "Giay phep kinh doanh phai la file anh hoac PDF", statusCode: 400 },
  CONTRACT_POWER_OF_ATTORNEY_FILE_INVALID: { code: "ERR_CONTRACT_040", message: "Giay uy quyen phai la file anh hoac PDF", statusCode: 400 },
  CONTRACT_GDP_FILE_INVALID: { code: "ERR_CONTRACT_041", message: "GDP phai la file anh hoac PDF", statusCode: 400 },
  CONTRACT_CCDDK_FILE_INVALID: { code: "ERR_CONTRACT_042", message: "CCDDK phai la file anh hoac PDF", statusCode: 400 },
  CONTRACT_HANDWRITTEN_SIGNATURE_INVALID: { code: "ERR_CONTRACT_043", message: "Anh chu ky tay khong hop le", statusCode: 400 },
  GRPC_LICENSE_INPUT_MISSING: { code: "ERR_LICENSE_GRPC_001", message: "Thieu licenseKey hoac softwareId", statusCode: 400 },
  PDF_WATERMARK_LOGO_NOT_FOUND: (path) => ({ code: "ERR_PDF_001", message: `Khong tim thay watermark logo tai ${path}`, statusCode: 500 }),
  PDF_UNICODE_FONT_NOT_FOUND: { code: "ERR_PDF_002", message: "Khong tim thay font Unicode, hay cau hinh CONTRACT_FONT_PATH den file .ttf", statusCode: 500 },
  PDF_BYTE_RANGE_MISSING: { code: "ERR_PDF_003", message: "PDF signature placeholder thieu /ByteRange", statusCode: 500 },
  PDF_CONTENTS_MISSING: { code: "ERR_PDF_004", message: "PDF signature placeholder thieu /Contents", statusCode: 500 },
  PDF_CONTENTS_HEX_INVALID: { code: "ERR_PDF_005", message: "PDF signature /Contents hex placeholder khong hop le", statusCode: 500 },
  PDF_BYTE_RANGE_TOO_LONG: { code: "ERR_PDF_006", message: "PDF ByteRange replacement dai hon placeholder", statusCode: 500 },
  PDF_INCREMENTAL_STRUCTURE_UNSUPPORTED: { code: "ERR_PDF_007", message: "Cau truc PDF khong ho tro ky incremental", statusCode: 500 },
  PDF_SIGNATURE_FORM_MISSING: { code: "ERR_PDF_008", message: "Thieu PDF signature form cho ky incremental", statusCode: 500 },
  PDF_PAGE_OR_ACROFORM_MISSING: { code: "ERR_PDF_009", message: "Thieu PDF page hoac AcroForm object", statusCode: 500 },
  PDF_SIGNATURE_HEX_INVALID: { code: "ERR_PDF_010", message: "signatureHex phai la chuoi hex hop le", statusCode: 500 },
  PDF_SIGNATURE_HEX_TOO_LONG: (actual, maximum) => ({ code: "ERR_PDF_011", message: `signatureHex dai hon vung placeholder (${actual}/${maximum})`, statusCode: 500 }),
  PDF_HANDWRITTEN_STRUCTURE_UNSUPPORTED: { code: "ERR_PDF_012", message: "Cau truc PDF khong ho tro ky tay incremental", statusCode: 500 },
  PDF_SIGNATURE_PAGE_MISSING: { code: "ERR_PDF_013", message: "Thieu PDF signature page cho ky tay incremental", statusCode: 500 },
  PDF_PAGE_OBJECT_MISSING: { code: "ERR_PDF_014", message: "Thieu PDF page object cho ky tay incremental", statusCode: 500 },
};

module.exports = ErrorCodes;
